export const ADD_MARKER = 'ADD_MARKER';
export const DELETE_MARKER = 'DELETE_MARKER';
export const EDIT_MARKER = 'EDIT_MARKER';
export const SET_FOUND_MARKERS = 'SET_FOUND_MARKERS';
export const CLEAR_FOUND_MARKERS = 'CLEAR_FOUND_MARKERS';
